### ISSUE TITLE
Volatile

### ISSUE THREAD

**Issue by rudolfbyker** [dhylands/TimerUART#1]
Is the use of `volatile` in the `struct` declaration strictly necessary?

``` C
volatile struct
{
    uint8_t     m_getIdx;
    uint8_t     m_putIdx;
    uint8_t     m_entry[ myQ_SIZE ];
} myQ;
```

**Comment by dhylands** [comment]
I believe that it is. If you were to enter an infinite while loop waiting for new data and the compiler optimized m_getIdx into a register, then you would never see the new data (this assumes that you have say an interrupt which increments m_getIdx when a new character arrives).

**Comment by braucadr** [comment]
In the templatized version you declare the indices m_getIdx and m_putIdx volatile, which I agree is necessary for the reasons mentioned above.
But why is the instance declared volatile as well in the example?
`volatile CBUF< uint8_t, 64, char >   myQ;`
When using it this way, I get a compiler error at the call of `IsEmpty()`:
`while (!myQ->IsEmpty()) { ... }`
_passing 'volatile CBUF<uint8_t, 64, char>' as 'this' argument discards qualifiers [-fpermissive]_

**Comment by dhylands** [comment]
I don't think that the instance needs to be volatile. Looking through the history, it looks like I added the volatile specifically to the example instance, but as you say, I don't think its needed (and I should remove it).

I normally use the C macros and not the C++ class, so I probably just never ran into the errors and/or the compiler may be more strict about things.

**Comment by dhylands** [comment]
I just pushed a change which removes the volatile from the comment for the C++ example.

**Comment by rudolfbyker** [comment]
Are you sure you pushed the change? There is only one commit in this repository.

By the way, thanks. I've used this code in many different projects with great success.

**Comment by dhylands** [comment]
I'm away from my main computer - I'll have to check next week when I get home.

**Comment by dhylands** [comment]
It looks like I pushed the change to my main projects repo and not here. This CBUF.h now matches that one.
